name: diffdock-pocket-cpu
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.17
  - pip=23.3.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - openmm=7.6.0
  - pip:
    - pdbfixer @ git+https://github.com/openmm/pdbfixer@1.9
    - torch_geometric==2.4.0
    - torch-scatter==2.1.0
    - torch-sparse==0.6.17
    - torch-cluster==1.6.1
    - torch-spline-conv==1.2.2
    - e3nn==0.5.1
    - PyYAML==6.0.1
    - rdkit==2023.3.3
    - pandas==2.1.1
    - biopython==1.81
    - networkx==3.2
    - spyrmsd==0.6.0
    - scipy==1.11.3
    - fair-esm[esmfold]==2.0.0
    - dllogger @ git+https://github.com/NVIDIA/dllogger.git
